<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-UQSL3JM" name="TestRunner.TestRunner" tests="14" failures="2" timestamp="2022-05-24T23:02:02 EET" time="348.043" errors="0">
  <testcase name="runScenario" time="26.121" classname="TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps.SliderWrapper.IphonePageOpen(SliderWrapper.java:42)
at ✽.Iphone page should be opened(file:///D:/MyWork/Udacity/2nd_Project_Automation/Ecommerce_project/src/main/resources/Features/6-Slider.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="39.929" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="22.312" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="21.540" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="44.093" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="29.371" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="17.740" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="17.123" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="21.718" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="30.308" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="17.563" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="21.389" classname="TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps.SliderWrapper.NokiaPageOpen(SliderWrapper.java:35)
at ✽.Nokia page should be opened(file:///D:/MyWork/Udacity/2nd_Project_Automation/Ecommerce_project/src/main/resources/Features/6-Slider.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="19.154" classname="TestRunner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="19.682" classname="TestRunner.TestRunner"/>
  <system-out/>
</testsuite> <!-- TestRunner.TestRunner -->
